/*
 * This Groovy source file was auto generated by running 'gradle buildInit --type groovy-library'
 * by 'Di' at '8/08/17 12:18 PM' with Gradle 2.12
 *
 * @author Di, @date 8/08/17 12:18 PM
 */
class Library {
    boolean someLibraryMethod() {
        true
    }
}
