language: groovy

jdk:
  - oraclejdk8

script:
  - ./gradlew cucumber -Ddriver="firefox" spock -Ddriver="firefox" unitTest

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
