SOAP:
  GetCountriesAvailable: /src/cucumberTest/resources/payload/webservice/soap/GetCountriesAvailable/request.xml
MOCK:
  greet: /greet/mock.txt
  greetJSON: /greetJSON/mock.json
  greetXML: /greetXML/mock.xml