/*
 * This Spock specification was auto generated by running the Gradle 'init' task
 * by 'Di' at '8/08/17 12:18 PM' with Gradle 2.12
 *
 * @author Di, @date 8/08/17 12:18 PM
 */

import spock.lang.Specification

class LibraryTest extends Specification{
    def "someLibraryMethod returns true"() {
        setup:
        Library lib = new Library()
        when:
        def result = lib.someLibraryMethod()
        then:
        result == true
    }
}
